import React from 'react';

const Productdetail = [
    {
        /* Пазлы */
        id: 1,
        Title: "Пазл Морские Жители",
        Cat: 'Пазлы',
        Price: "230₽",
        PriceTotal: "230₽",
        Count: 1,
        Manufacturer: "USA",
        Img: './images/puzzles/пазлы1.png',
    },
    {
        id: 2,
        Title: "Пазл ферма",
        Cat: 'Пазлы',
        Price: "300₽",
        PriceTotal: "300₽",
        Count: 1,
        Manufacturer: "USA",
        Img: './images/puzzles/пазлы2.png',
    },
    {
        id: 3,
        Title: "Пазл Барбоскины",
        Cat: 'Пазлы',
        Manufacturer: "USA",
        Price: "400₽",
        PriceTotal: "400₽",
        Count: 1,
        Img: './images/puzzles/пазлы3.png',
    },
    {
        id: 4,
        Title: "Пазл Буренка Даша",
        Cat: 'Пазлы',
        Manufacturer: "USA",
        Price: "420₽",
        PriceTotal: "420₽",
        Count: 1,
        Img: './images/puzzles/пазлы4.png',
    },
    {
        id: 5,
        Title: "Пазл три кота",
        Cat: 'Пазлы',
        Manufacturer: "USA",
        Price: "1200₽",
        PriceTotal: "1200₽",
        Count: 1,
        Img: './images/puzzles/пазлы6.png',
    },
    {
        id: 6,
        Title: "Пазл три поросенка",
        Cat: 'Пазлы',
        Manufacturer: "USA",
        Price: "2200₽",
        Img: './images/puzzles/пазлы7.png',
    },
    {
        id: 7,
        Title: "Пазл животные",
        Cat: 'Пазлы',
        Manufacturer: "USA",
        Price: "2200₽",
        PriceTotal: "2200₽",
        Count: 1,
        Img: './images/puzzles/пазлы8.png',
    },
    {
        id: 8,
        Title: "Пазл Смешарики",
        Cat: 'Пазлы',
        Price: "2290₽",
        PriceTotal: "2290₽",
        Count: 1,
        Manufacturer: "USA",
        Img: './images/puzzles/пазлы9.png',
    },
    {
        id: 9,
        Title: "Пазл карсная машина",
        Cat: 'Пазлы',
        Manufacturer: "China",
        Price: "2662₽",
        PriceTotal: "2662₽",
        Count: 1,
        Img: './images/puzzles/пазлы10.png',
    },
    /* Плюшевые игрушки */
    {
        id: 10,
        Title: "Плюшевый мишка",
        Cat: 'Плюшевые',
        Manufacturer: "China",
        Price: "5662₽",
        PriceTotal: "5662₽",
        Count: 1,
        Img: './images/plushes/plush-1.png',
    },
    {
        id: 11,
        Title: "Милый лев",
        Cat: 'Плюшевые',
        Price: "4555₽",
        PriceTotal: "4555₽",
        Count: 1,
        Manufacturer: "China",
        Img: './images/plushes/plush-2.png',
    },
    /* машины*/
    {
        id: 12,
        Title: "Зеленая машина",
        Cat: 'Машины',
        Manufacturer: "China",
        Price: "1155₽",
        PriceTotal: "1155₽",
        Count: 1,
        Img: './images/cars/машина1.png',
    },
    {
        id: 13,
        Title: "Красная спортивная машина",
        Cat: 'Машины',
        Price: "7119₽",
        PriceTotal: "7119₽",
        Count: 1,
        Manufacturer: "China",
        Img: './images/cars/машина5.png',
    },
    {
        id: 14,
        Title: "Желтый трактор",
        Cat: 'Машины',
        Manufacturer: "China",
        Price: "5225₽",
        PriceTotal: "5225₽",
        Count: 1,
        Img: './images/cars/машина3.png',
    },
    /*meccano */
    {
        id: 15,
        Title: "Робот",
        Cat: 'Конструкторы',
        Manufacturer: "China",
        Price: "6511₽",
        PriceTotal: "6511₽",
        Count: 1,
        Img: './images/meccano/meccano-1.png',
    },
    {
        id: 16,
        Title: "Желтый трансформер",
        Cat: 'Конструкторы',
        Price: "2289₽",
        PriceTotal: "2289₽",
        Count: 1,
        Manufacturer: "China",
        Img: './images/meccano/meccano-2.png',
    },
    /* Куклы */
    {
        id: 17,
        Title: "Кукла Аврора",
        Cat: 'Куклы',
        Price: "2275₽",
        PriceTotal: "2275₽",
        Count: 1,
        Manufacturer: "China",
        Img: './images/dolls/doll5.png',
    },
    {
        id: 18,
        Title: "Рапунцель",
        Cat: 'Куклы',
        Price: "2285₽",
        PriceTotal: "2285₽",
        Count: 1,
        Manufacturer: "USA",
        Img: './images/dolls/doll6.png',
    },
    {
        id: 19,
        Title: "Кукла Барби",
        Cat: 'Куклы',
        Manufacturer: "USA",
        Price: "2265₽",
        PriceTotal: "2265₽",
        Count: 1,
        Img: './images/dolls/doll1.png',
    },
    {
        id: 20,
        Title: "Кукла Барби в нарядном платье",
        Cat: 'Куклы',
        Manufacturer: "USA",
        Price: "1000₽",
        PriceTotal: "1000₽",
        Count: 1,
        Img: './images/dolls/doll2.png',
    },
    {
        id: 21,
        Title: "Кукла Барби Фея",
        Cat: 'Куклы',
        Manufacturer: "USA",
        Price: "752₽",
        PriceTotal: "752₽",
        Count: 1,
        Img: './images/dolls/doll3.png',
    },
    {
        id: 22,
        Title: "Кукла Эльза",
        Cat: 'Куклы',
        Price: "1175₽",
        PriceTotal: "1175₽",
        Count: 1,
        Manufacturer: "USA",
        Img: './images/dolls/doll4.png',
    },
    /* доп. meccano*/
    {
        id: 23,
        Title: "Белый робот-собака",
        Cat: 'Конструкторы',
        Price: "1199₽",
        PriceTotal: "1199₽",
        Count: 1,
        Manufacturer: "China",
        Img: './images/meccano/meccano-3.png',
    },
    {
        id: 24,
        Title: "Белый робот",
        Cat: 'Конструкторы',
        Price: "1299₽",
        PriceTotal: "1299₽",
        Count: 1,
        Manufacturer: "China",
        Img: './images/meccano/meccano-4.png',
    },
    {
        id: 25,
        Title: "Бирюзовый робот",
        Cat: 'Конструкторы',
        Price: "999₽",
        PriceTotal: "999₽",
        Count: 1,
        Manufacturer: "China",
        Img: './images/meccano/meccano-5.png',
    },
    /* доп. plushes*/
    {
        id: 26,
        Title: "Милый кот",
        Cat: 'Плюшевые',
        Price: "799₽",
        PriceTotal: "799₽",
        Count: 1,
        Manufacturer: "China",
        Img: './images/plushes/plush-3.png',
    },
    {
        id: 27,
        Title: "Большой кот",
        Cat: 'Плюшевые',
        Price: "5999₽",
        PriceTotal: "5999₽",
        Count: 1,
        Manufacturer: "China",
        Img: './images/plushes/plush-4.png',
    },
    {
        id: 28,
        Title: "Милый серый енот",
        Cat: 'Плюшевые',
        Price: "4400₽",
        PriceTotal: "4400₽",
        Count: 1,
        Manufacturer: "China",
        Img: './images/plushes/plush-5.png',
    },
    /* доп. cars*/
    {
        id: 29,
        Title: "Белая спортивная машина",
        Cat: 'Машины',
        Price: "999₽",
        PriceTotal: "999₽",
        Count: 1,
        Manufacturer: "China",
        Img: './images/cars/машина4.png',
    }, 
    {
        id: 30,
        Title: "Белый кролик",
        Cat: 'Плюшевые',
        Price: "999₽",
        PriceTotal: "999₽",
        Count: 1,
        Manufacturer: "China",
        Img: './images/plushes/plush-7.png',
    }, 
    {
        id: 31,
        Title: "Большая книга сказок",
        Cat: 'Книги',
        Price: "999₽",
        PriceTotal: "999₽",
        Count: 1,
        Manufacturer: "China",
        Img: './images/books/700-nw (1).png',
       
    }, 
    {
        id: 32,
        Title: "Маленькие человечки",
        Cat: 'Книги',
        Price: "949₽",
        PriceTotal: "949₽",
        Count: 1,
        Manufacturer: "China",
        Img: './images/books/700-nw.png',
        
    }, 
    {
        id: 33,
        Title: "Горшошчек каши",
        Cat: 'Книги',
        Price: "2199₽",
        PriceTotal: "2199₽",
        Count: 1,
        Manufacturer: "China",
        Img: './images/books/700-nw (2).png',
        
    }, 
    {
        id: 34,
        Title: "Принцесса на горошине",
        Cat: 'Книги',
        Price: "1199₽",
        PriceTotal: "1199₽",
        Count: 1,
        Manufacturer: "China",
        Img: './images/books/700-nw (3)_pixian_ai.png',
      
    }, 
    {
        id: 35,
        Title: "Дюймовочка",
        Cat: 'Книги',
        Price: "1199₽",
        PriceTotal: "1199₽",
        Count: 1,
        Manufacturer: "China",
        Img: './images/books/80bc3b3f963eda4c55482d4770407d72_pixian_ai.png',
        
    }, 
];

export default Productdetail;